name: Implantar em Staging
on:
  workflow_dispatch:
    inputs:
      versao:
        description: 'Qual o número completo da versão a ser implentada em Staging? (Ex.: 1.7.2)'
        required: true

jobs:
  deploy-em-staging:
    runs-on: ubuntu-latest

    environment: staging

    env:
      INPUT_VERSAO: ${{ github.event.inputs.versao }}
      CODIGO_SECRETO: ${{ secrets.CODIGO_SECRETO }}
    
    steps:
      - run: echo 'variavel secreta:'
      - run: echo $CODIGO_SECRETO
      - run: echo "Versão Desejada $INPUT_VERSAO"
      - run: echo 'FFIMMMM'